version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_tailor
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass1234!
      POSTGRES_DB: smarttailor
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
