server:
  port: 8090
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: SmartTailor
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: u11se03r@gmail.com
    password: tkvb tixr buig chlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 1800000
  refresh:
    expiration: 604800000
  secret: 3167ceee9cb36d05a553fd48752e077e8e2c7edef0c046f7bc7a38678f7bd8da

cloudinary:
  cloud-name: dn0akydmv
  api-key: 883779744122919
  api-secret: 2q8MUhDG4sUjtN47HZS823Zxjko

rabbitmq:
  host: 46.101.135.225

app:
  firebase-configuration-file : "firebase/smarttailorfirebase-firebase-adminsdk-bm52t-751b36d6eb.json"
