package kg.neobis.smarttailor.enums;

public enum AccessRight {
    CREATE_POSITION,
    CHANGE_POSITION_ACCESS_RIGHTS,
    DELETE_POSITION,
    ASSIGN_EMPLOYEE_TO_ORDER,
    INVITE_EMPLOYEE,
    REMOVE_EMPLOYEE_FROM_ORDER,
    REMOVE_EMPLOYEE,
    CHANGE_ORDER_STATUS,
    COMPLETE_ORDER,
    SEND_REQUEST_TO_EXECUTE_ORDER
}