package kg.neobis.smarttailor.enums;

public enum AccessRight {
    TAKE_ORDER,
    ASSIGN_EMPLOYEE_TO_ORDER,
    REMOVE_EMPLOYEE_FROM_ORDER,
    CHANGE_ORDER_STATUS,
    CANCEL_ORDER,
    COMPLETE_ORDER,
    REMOVE_EMPLOYEE,
    DELETE_POSITION,
    CREATE_POSITION,
    CHANGE_POSITION_ACCESS_RIGHTS,
    INVITE_EMPLOYEE,
    CHANGE_POSITION_WEIGHT
}