package kg.neobis.smarttailor.enums;

public enum AccessRight {
    CREATE_POSITION,
    CHANGE_POSITION_ACCESS_RIGHTS,
    DELETE_POSITION,
    ADD_EMPLOYEE,
    DELETE_EMPLOYEE,
    CHANGE_ORDER_STATUS,
    DELETE_ORDER,
    SEND_REQUEST_TO_EXECUTE_ORDER
}